### PR TITLE
increasing tolerance for whitespaces | nav-bar-description for rename arrow right

### PR DESCRIPTION
**Pull request by mafo3186**
@r-prem 
- This pull request is related to #169 
You find the intended contribution in this commit: 15f47c0ccbb656328340874041aa0e914162ec6c

The other commits are 

- an change of the label in the Relational Algebra toolbar  for the right arrow operation c93bbd0de0594934d7aaf9076559296a7e45d0bb
- our added gists for the HSD as maintainer (this was not intended to contribute - we possibly move those gists somewhere else) 26e4762d32da591ed1de18ab80e6052ede8c792f)
-  fixed typo in ReadMe c7d454045319c6902f2ac43adfdf97878fe514f3) 
- a change of text in an error-message to cover the problems described in #169   - actually the changes do not show up running relax 7b76a63043bdb16e6326bbddcf9c6146f79541a6

Sorry for mixing up everything - next time I will better separate commits and pull requests. Anyways I would be glad if you would take a look at it!

### CODE REVIEW

**Comment by mafo3186** [comment]
@r-prem Please let me know if I can/should do anything.

**Comment by r-prem** [comment]
@mafo3186 Have been quite busy, will check it out this Thursday / Friday

**Review by r-prem — CHANGES_REQUESTED** [review]
Please format the json files properly to match the development branch, this is causing merge conflicts, as it is written completely in one line. If possible please also implement the new keys that have been added in my last commit.

**Comment by mafo3186** [comment]
> Please format the json files properly to match the development branch, this is causing merge conflicts, as it is written completely in one line. If possible please also implement the new keys that have been added in my last commit.

@r-prem Sorry for taking so long. I reformatted the json-files and added all keys that I found additionally in the current json-files - also in kt and pt where they didn't exist yet. There is also still a difference in "calc.menu.create-own-dataset-text" - I was not sure If you really wanted to have the sentence unfinished.

Can you already proceed right now, or can/should I do anything else?

**Comment by r-prem** [comment]
@mafo3186 Sorry for the late response, was on holiday. Just accepted it, and will publish a new version sometime during the day.

**Comment by mafo3186** [comment]
@r-prem Thank you!

**Pull request merged**
